POST https://fakhrul.azurewebsites.net/loginHost
Content-Type: application/json

{
  "idNumber": "20223112",
  "password": "12345"
}

###
### POST Request to viewVisitor Endpoint
###

POST http://localhost:3000/viewVisitor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTEyIiwicm9sZSI6Im93bmVyIiwiaWF0IjoxNzA0NTM4ODYzfQ.twmOo7M8bEFveUYRId2UOQ2IYsVoMP8HkqOrmDUDQOI

###

POST http://localhost:3000/retrieveVisitor
Content-Type: application/json

{
  "idNumber": "123456789",
  "password": "qwerty"
}

###

POST http://localhost:3000/loginAdmin
Content-Type: application/json

{
  "idNumber": "20223119",
  "password": "67890"
}

###

POST http://localhost:3000/loginSecurity
Content-Type: application/json

{
  "idNumber": "20223113",
  "password": "12345"
}

###

POST http://localhost:3000/loginHost
Content-Type: application/json

{
  "idNumber": "20223112",
  "password": "12345"
}

###

POST http://localhost:3000/issuepassVisitor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTEyIiwicm9sZSI6Ikhvc3QiLCJpYXQiOjE3MDQ1NDg4OTN9.0axdDfX7nE_lmsrunrPe5kEBp-YrAiKXcVJSkPK93-0

{
  "role": "Host or security",
  "name": "Visitor Name",
  "idNumber": "Visitor ID",
  "documentType": "Type",
  "gender": "Gender",
  "birthDate": "YYYY-MM-DD",
  "age": "Age",
  "documentExpiry": "YYYY-MM-DD",
  "company": "Company Name",
  "TelephoneNumber": "Phone Number",
  "vehicleNumber": "Vehicle Number",
  "category": "Category",
  "ethnicity": "Ethnicity",
  "photoAttributes": "Photo Attributes",
  "passNumber": "Pass Number",
  "password": "Password",
  "idNumberHost": "Host ID"
}

###

POST http://localhost:3000/registerHost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTEzIiwicm9sZSI6InNlY3VyaXR5IiwiaWF0IjoxNzA0NTQ4MDk2fQ.9z86tA_YIRnTanX4C9lm5HfbakJDZhGyGqMOVZ6y0r4

{
  "role": "Host",
  "name": "Zaid",
  "idNumber": "98765",
  "email": "zaid@email.com",
  "password": "zaid123",
  "phoneNumber": "0168219343"
}

###

POST http://localhost:3000/viewHost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTE5Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0NTUwNDg2fQ.kD7E7Wf33BQyN_omJEzVg9a5tPXy_0cFmJcDEYnXR1Q

###

POST http://localhost:3000/retrievePhoneNumber
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTEzIiwicm9sZSI6InNlY3VyaXR5IiwiaWF0IjoxNzA0NTUzMDI0fQ.u-TDvcce6emXUOGCnHieQMc3sV3tOfwmyxH-hUiNKyU

{
  "idNumber": "987654321"
}

###

POST http://localhost:3000/manageRole
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTE5Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0NTU1NTAzfQ.9qK3vocFS68JRntEBQJ0z6mHp4lZ3PbZkW8BRkLb868

{
  "idNumber": "345657890",
  "role": "security"
}

###

POST http://localhost:3000/loginAdmin
Content-Type: application/json

{
  "idNumber": "20223119",
  "password": "sdads"
}
