POST https://fakhrul.azurewebsites.net/loginOwner
Content-Type: application/json

{
  "idNumber": "20223112",
  "password": "12345"
}

###
### POST Request to viewVisitor Endpoint
###

POST http://localhost:3000/viewVisitor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTEyIiwicm9sZSI6Im93bmVyIiwiaWF0IjoxNzA0NTM4ODYzfQ.twmOo7M8bEFveUYRId2UOQ2IYsVoMP8HkqOrmDUDQOI

###

POST http://localhost:3000/retrieveVisitor
Content-Type: application/json

{
  "idNumber": "123456789",
  "password": "qwerty"
}

###

POST http://localhost:3000/loginAdmin
Content-Type: application/json

{
  "idNumber": "20223117",
  "password": "6789"
}
